
export const GET_ALL_RESULTS_SUCCESS = 'GET_ALL_RESULTS_SUCCESS';
export const GET_ALL_RESULTS_ERROR = 'GET_ALL_RESULTS_ERROR';
export const ADD_RESULTS_SUCCESS = 'ADD_RESULTS_SUCCESS';
export const ADD_RESULTS_ERROR = 'ADD_RESULTS_ERROR';

